openapi: 3.0.3
info:
  title: GetFundHoldings API
  description: |
    API specification for fund holdings data from the GetFundHoldings pipeline.
    
    This API provides access to enriched fund holdings data stored in Cloudflare R2.
    Data is sourced from SEC N-PORT filings and enriched with ticker symbols via OpenFIGI.
    
    ## Data Organization
    - Holdings data is organized by fund ticker
    - Latest data is available at `/latest/{fund_ticker}/holdings_enriched.json`
    - Historical data may be available at `/historical/{fund_ticker}/{timestamp}/`
    
    ## Data Freshness
    - Data is updated as new N-PORT filings become available
    - Typical update frequency: quarterly (following SEC filing deadlines)
    - Each response includes timestamps for data provenance
    
  version: 1.0.0
  contact:
    name: GetFundHoldings Support
    url: https://getfundholdings.com
    email: admin@getfundholdings.com
  license:
    name: MIT
    url: https://opensource.org/licenses/MIT

servers:
  - url: https://your-r2-domain.com
    description: Production R2 Storage
  - url: https://dev-your-r2-domain.com
    description: Development R2 Storage

paths:
  /latest/{fund_ticker}/holdings_enriched.json:
    get:
      summary: Get latest holdings for a fund
      description: |
        Retrieve the most recent enriched holdings data for a specific fund ticker.
        
        Returns a JSON object containing metadata about the holdings dataset and
        an array of individual security holdings with ticker enrichment.
        
      parameters:
        - name: fund_ticker
          in: path
          required: true
          description: Fund ticker symbol (e.g., 'IVV', 'VOO', 'SPY')
          schema:
            type: string
            pattern: '^[A-Z0-9]{1,10}$'
            example: 'IVV'
      responses:
        '200':
          description: Holdings data retrieved successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HoldingsResponse'
              examples:
                ivv_example:
                  summary: iShares Core S&P 500 ETF (IVV)
                  value:
                    metadata:
                      fund_ticker: 'IVV'
                      cik: '1100663'
                      total_holdings: 503
                      data_timestamp: '20250711_143022'
                      source_file: 'holdings_enriched_IVV_1100663_S000004310_20250711_20250711_143022.csv'
                      upload_timestamp: '2025-07-11T14:30:22.123456Z'
                    holdings:
                      - name: 'Apple Inc'
                        title: 'Apple Inc'
                        cusip: '037833100'
                        ticker: 'AAPL'
                        value_usd: 1500000000.00
                        percent_value: 0.074
                        fund_ticker: 'IVV'
                        series_id: 'S000004310'
                        # ... additional fields
        '404':
          description: Fund ticker not found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
              example:
                error: 'Fund ticker "XYZ" not found'
                timestamp: '2025-07-11T14:30:22.123456Z'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  schemas:
    HoldingsResponse:
      type: object
      description: Complete fund holdings response structure
      required:
        - metadata
        - holdings
      properties:
        metadata:
          $ref: '#/components/schemas/HoldingsMetadata'
        holdings:
          type: array
          description: Array of individual security holdings
          items:
            $ref: '#/components/schemas/Holding'

    HoldingsMetadata:
      type: object
      description: Metadata about the holdings dataset
      required:
        - fund_ticker
        - cik
        - total_holdings
        - data_timestamp
        - upload_timestamp
      properties:
        fund_ticker:
          type: string
          description: Fund ticker symbol
          pattern: '^[A-Z0-9]{1,10}$'
          example: 'IVV'
        cik:
          type: string
          description: SEC CIK identifier for the fund company
          pattern: '^[0-9]{1,10}$'
          example: '1100663'
        total_holdings:
          type: integer
          description: Total number of holdings in the dataset
          minimum: 0
          example: 503
        data_timestamp:
          type: string
          description: Processing timestamp in YYYYMMDD_HHMMSS format
          pattern: '^[0-9]{8}_[0-9]{6}$'
          example: '20250711_143022'
        source_file:
          type: string
          description: Original CSV filename from the data pipeline
          example: 'holdings_enriched_IVV_1100663_S000004310_20250711_20250711_143022.csv'
        upload_timestamp:
          type: string
          format: date-time
          description: ISO 8601 timestamp when data was uploaded to R2
          example: '2025-07-11T14:30:22.123456Z'

    Holding:
      type: object
      description: Individual security holding information
      required:
        - name
        - title
        - balance
        - units
        - currency
        - value_usd
        - percent_value
        - payoff_profile
        - asset_category
        - issuer_category
        - investment_country
        - is_restricted_security
        - fair_value_level
        - is_cash_collateral
        - is_non_cash_collateral
        - is_loan_by_fund
        - source_file
        - report_period_date
        - enrichment_datetime
        - fund_ticker
        - series_id
      properties:
        name:
          type: string
          description: Security name
          example: 'Apple Inc'
        lei:
          type: string
          nullable: true
          description: Legal Entity Identifier
          example: 'HWUPKR0MPOU8FGXBT394'
        title:
          type: string
          description: Security title/description
          example: 'Apple Inc'
        cusip:
          type: string
          nullable: true
          description: CUSIP identifier (9 characters)
          pattern: '^[0-9A-Z]{9}$'
          example: '037833100'
        isin:
          type: string
          nullable: true
          description: ISIN identifier (12 characters)
          pattern: '^[A-Z]{2}[0-9A-Z]{10}$'
          example: 'US0378331005'
        other_id:
          type: string
          nullable: true
          description: Other identifier value
        other_id_desc:
          type: string
          nullable: true
          description: Other identifier description
        balance:
          type: number
          description: Security balance/shares
          example: 12500000.0
        units:
          type: string
          description: Units of measurement
          example: 'NS'
        currency:
          type: string
          description: Currency code
          pattern: '^[A-Z]{3}$'
          example: 'USD'
        value_usd:
          type: number
          description: Market value in USD
          example: 1500000000.00
        percent_value:
          type: number
          description: Percentage of total portfolio value (decimal)
          minimum: -10.0
          maximum: 10.0
          example: 0.074
        payoff_profile:
          type: string
          description: Payoff profile
          example: 'Long'
        asset_category:
          type: string
          description: Asset category code
          example: 'EC'
        issuer_category:
          type: string
          description: Issuer category code
          example: 'CORP'
        investment_country:
          type: string
          description: Investment country code
          pattern: '^[A-Z]{2}$'
          example: 'US'
        is_restricted_security:
          type: string
          enum: ['Y', 'N', '']
          description: Restricted security flag
          example: 'N'
        fair_value_level:
          type: string
          description: Fair value level
          example: '1'
        is_cash_collateral:
          type: string
          enum: ['Y', 'N', '']
          description: Cash collateral flag
          example: 'N'
        is_non_cash_collateral:
          type: string
          enum: ['Y', 'N', '']
          description: Non-cash collateral flag
          example: 'N'
        is_loan_by_fund:
          type: string
          enum: ['Y', 'N', '']
          description: Loan by fund flag
          example: 'N'
        loan_value:
          type: number
          nullable: true
          description: Loan value if applicable
        source_file:
          type: string
          description: Source N-PORT XML filename
          example: 'nport_1100663_S000004310_0001752724_25_119791.xml'
        report_period_date:
          type: string
          description: N-PORT report period date
          pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}$'
          example: '2025-03-31'
        ticker:
          type: string
          nullable: true
          description: Ticker symbol from OpenFIGI API enrichment
          example: 'AAPL'
        enrichment_datetime:
          type: string
          format: date-time
          description: Timestamp when ticker enrichment was performed
          example: '2025-07-11T14:30:22.123456Z'
        fund_ticker:
          type: string
          description: Fund ticker symbol
          pattern: '^[A-Z0-9]{1,10}$'
          example: 'IVV'
        series_id:
          type: string
          description: SEC series identifier
          pattern: '^S[0-9]{9}$'
          example: 'S000004310'

    ErrorResponse:
      type: object
      description: Error response structure
      required:
        - error
        - timestamp
      properties:
        error:
          type: string
          description: Error message
          example: 'Fund ticker "XYZ" not found'
        timestamp:
          type: string
          format: date-time
          description: Error timestamp
          example: '2025-07-11T14:30:22.123456Z'

tags:
  - name: holdings
    description: Fund holdings data operations