#!/usr/bin/env python3
"""
Pandera schema definitions for summary ticker data structures.
"""

from datetime import datetime
from typing import Optional

import pandas as pd
import pandera.pandas as pa
from pandera.typing import DataFrame, Series


class SummaryTickerSchema(pa.DataFrameModel):
    """
    Schema for summary ticker data generated by create_summary_tickers.py.

    This schema defines the structure of the summary ticker DataFrame that contains
    metadata about each ETF ticker available for upload to R2.
    """

    # Core ticker identification
    ticker: Series[str] = pa.Field(description="ETF ticker symbol (e.g., 'IVV', 'SPY')")
    name: Series[str] = pa.Field(description="Fund name from series metadata")
    title: Series[str] = pa.Field(description="Fund title (currently same as name)")

    # SEC identification
    cik: Series[str] = pa.Field(description="10-digit SEC CIK identifier")
    series_id: Series[str] = pa.Field(description="SEC series identifier")

    # Latest data file metadata
    latest_report_date: Series[str] = pa.Field(
        description="Latest N-PORT report date (YYYYMMDD format)"
    )
    latest_timestamp: Series[str] = pa.Field(
        description="Latest file timestamp (YYYYMMDD_HHMMSS format)"
    )
    latest_file: Series[str] = pa.Field(description="Latest enriched holdings filename")

    # Processing metadata
    data_updated: Series[str] = pa.Field(
        description="ISO timestamp when summary was generated"
    )

    class Config:
        strict = True
        coerce = True


def validate_summary_ticker(df: pd.DataFrame) -> pd.DataFrame:
    """
    Validate a summary ticker dataframe against the schema.

    Args:
        df: DataFrame to validate

    Returns:
        Validated DataFrame

    Raises:
        pandera.errors.SchemaError: If validation fails
    """
    return SummaryTickerSchema.validate(df)


# Type alias for convenience
SummaryTickerDF = DataFrame[SummaryTickerSchema]
